Repository Za-ply/Zaply-server, pull requests merged in 2025-05, with the labels that each got.

#17 FIX: jre 빌드 이미지를 변경하고, 도커 네트워크를 구성한다.
  .github/workflow/ci-cd.yml
  .github/workflows/ci-cd.yml
  Dockerfile
  src/main/java/org/zapply/product/global/config/SecurityConfig.java
  terraform/.gitignore
  terraform/network_module/variables.tf
  terraform/server_module/variables.tf
Labels: 🌏 Deploy

#20 FEAT: Facebook 계정을 연동하고 Access token을 장기 토큰으로 관리한다
  build.gradle
  src/main/java/org/zapply/product/domain/user/controller/AccountController.java
  src/main/java/org/zapply/product/domain/user/controller/AuthController.java
  src/main/java/org/zapply/product/domain/user/entity/Account.java
  src/main/java/org/zapply/product/domain/user/repository/AccountRepository.java
  src/main/java/org/zapply/product/domain/user/repository/MemberRepository.java
  src/main/java/org/zapply/product/domain/user/service/AccountService.java
  src/main/java/org/zapply/product/domain/user/service/UserService.java
  src/main/java/org/zapply/product/global/apiPayload/exception/GlobalErrorType.java
  src/main/java/org/zapply/product/global/config/SecurityConfig.java
  src/main/java/org/zapply/product/global/security/AuthDetails.java
  src/main/java/org/zapply/product/global/security/AuthDetailsService.java
  src/main/java/org/zapply/product/global/security/facebook/FacebookClient.java
  src/main/java/org/zapply/product/global/security/facebook/FacebookProfile.java
  src/main/java/org/zapply/product/global/security/facebook/FacebookToken.java
Labels: 💫 Feature

#21 FEAT: Object Storage를 연결하고, 워크플로우를 작성한다
  .github/workflows/ci-cd.yml
  build.gradle
  src/main/java/org/zapply/product/global/config/ObjectStorageConfig.java
  src/main/java/org/zapply/product/global/config/SecurityConfig.java
  src/main/java/org/zapply/product/global/healthCheck/controller/HealthCheckController.java
  src/main/java/org/zapply/product/global/objectStorage/controller/ImageController.java
  src/main/java/org/zapply/product/global/objectStorage/dto/ReadPreSignedUrlResponse.java
  src/main/java/org/zapply/product/global/objectStorage/service/ObjectStorageService.java
  src/test/java/org/zapply/product/global/objectStorage/controller/ImageControllerTest.java
  terraform/.gitignore
  terraform/main.tf
  terraform/storage_module/main.tf
  terraform/storage_module/outputs.tf
  terraform/storage_module/providers.tf
  terraform/storage_module/variables.tf
Labels: 💫 Feature

#23 FIX: 자체로그인 관련 수정사항을 반영한다
  src/main/java/org/zapply/product/domain/user/dto/response/MemberResponse.java
  src/main/java/org/zapply/product/domain/user/entity/Member.java
  src/main/java/org/zapply/product/domain/user/enumerate/MemberType.java
  src/main/java/org/zapply/product/global/apiPayload/exception/GlobalErrorType.java
  src/main/java/org/zapply/product/global/config/SecurityConfig.java
  src/main/java/org/zapply/product/global/security/AuthDetails.java
  src/main/java/org/zapply/product/global/security/facebook/FacebookClient.java
  src/main/java/org/zapply/product/global/security/jwt/JwtAccessDeniedHandler.java
  src/main/java/org/zapply/product/global/security/jwt/JwtAuthenticationHandler.java
Labels: ✨ Fix

#25 FEAT: 구글 소셜 로그인을 구현한다
  .github/workflows/ci-cd.yml
  .gitignore
  src/main/java/org/zapply/product/domain/user/entity/Member.java
  src/main/java/org/zapply/product/global/apiPayload/exception/GlobalErrorType.java
  src/main/java/org/zapply/product/global/config/SecurityConfig.java
  src/main/java/org/zapply/product/global/security/oAuth2/CustomOAuth2User.java
  src/main/java/org/zapply/product/global/security/oAuth2/CustomOAuth2UserService.java
  src/main/java/org/zapply/product/global/security/oAuth2/OAuth2SuccessHandler.java
Labels: 💫 Feature

#29 FEAT: 스레드 계정을 연동한다
  src/main/java/org/zapply/product/domain/user/controller/AccountController.java
  src/main/java/org/zapply/product/domain/user/repository/AccountRepository.java
  src/main/java/org/zapply/product/domain/user/service/AccountService.java
  src/main/java/org/zapply/product/global/apiPayload/exception/GlobalErrorType.java
  src/main/java/org/zapply/product/global/security/facebook/FacebookProfile.java
  src/main/java/org/zapply/product/global/security/facebook/FacebookToken.java
  src/main/java/org/zapply/product/global/security/threads/ThreadsClient.java
  src/main/java/org/zapply/product/global/security/threads/ThreadsProfile.java
  src/main/java/org/zapply/product/global/security/threads/ThreadsToken.java
Labels: 💫 Feature

#30 Fix: 스레드 API 연동 에러 타입을 추가한다
  src/main/java/org/zapply/product/global/apiPayload/exception/GlobalErrorType.java
Labels: ✨ Fix

#33 FIX: 회원가입 변동사항을 반영하고 주민등록번호 암호화, 약관동의 필드 추가, 유효성 검사 기능을 개발한다
  build.gradle
  src/main/java/org/zapply/product/domain/user/controller/AuthController.java
  src/main/java/org/zapply/product/domain/user/dto/request/AuthRequest.java
  src/main/java/org/zapply/product/domain/user/dto/response/MemberResponse.java
  src/main/java/org/zapply/product/domain/user/entity/Agreement.java
  src/main/java/org/zapply/product/domain/user/entity/Member.java
  src/main/java/org/zapply/product/domain/user/repository/MemberRepository.java
  src/main/java/org/zapply/product/domain/user/service/AuthService.java
  src/main/java/org/zapply/product/global/apiPayload/exception/GlobalErrorType.java
  src/main/java/org/zapply/product/global/security/jasypt/JasyptStringEncryptor.java
  src/main/java/org/zapply/product/global/security/oAuth2/CustomOAuth2UserService.java
Labels: ✨ Fix

#38 FEAT: 모니터링 환경을 구축한다
  .github/workflows/ci-cd.yml
  .gitignore
  build.gradle
  observability/docker-compose.yml
  observability/loki/config/local-config.yaml
  observability/prometheus/config/prometheus.yml
  observability/promtail/config/config.yml
  src/main/java/org/zapply/product/global/config/SecurityConfig.java
  src/main/resources/logback-spring.xml
  src/test/resources/logback-test.xml
Labels: 🌏 Deploy

#41 FEAT: Hashicorp vault에 토큰을 암호화하여 저장한다
  build.gradle
  src/main/java/org/zapply/product/domain/user/controller/AccountController.java
  src/main/java/org/zapply/product/domain/user/entity/Account.java
  src/main/java/org/zapply/product/domain/user/repository/AccountRepository.java
  src/main/java/org/zapply/product/domain/user/service/AccountService.java
  src/main/java/org/zapply/product/global/apiPayload/exception/GlobalErrorType.java
  src/main/java/org/zapply/product/global/security/jasypt/JasyptStringEncryptor.java
  src/main/java/org/zapply/product/global/threads/ThreadsReplyClient.java
  src/main/java/org/zapply/product/global/vault/VaultClient.java
  src/main/java/org/zapply/product/global/vault/VaultConfig.java
Labels: 💫 Feature

#43 FEAT: Threads에 미디어를 발행한다
  src/main/java/org/zapply/product/domain/posting/controller/PostingController.java
  src/main/java/org/zapply/product/domain/posting/dto/request/ThreadsPostingRequest.java
  src/main/java/org/zapply/product/domain/posting/dto/response/ThreadsPostingResponse.java
  src/main/java/org/zapply/product/domain/posting/entity/Posting.java
  src/main/java/org/zapply/product/domain/posting/repository/PostingRepository.java
  src/main/java/org/zapply/product/domain/project/repository/ProjectRepository.java
  src/main/java/org/zapply/product/domain/user/repository/AccountRepository.java
  src/main/java/org/zapply/product/domain/user/service/AccountService.java
  src/main/java/org/zapply/product/global/apiPayload/exception/GlobalErrorType.java
  src/main/java/org/zapply/product/global/facebook/FacebookClient.java
  src/main/java/org/zapply/product/global/facebook/FacebookProfile.java
  src/main/java/org/zapply/product/global/facebook/FacebookToken.java
  src/main/java/org/zapply/product/global/threads/ThreadsClient.java
  src/main/java/org/zapply/product/global/threads/ThreadsPostingClient.java
  src/main/java/org/zapply/product/global/threads/ThreadsProfile.java
  src/main/java/org/zapply/product/global/threads/ThreadsToken.java
Labels: 💫 Feature

#54 FIX: Facebook, Threads의 계정 연동 flow를 수정한다
  src/main/java/org/zapply/product/domain/user/controller/AccountController.java
  src/main/java/org/zapply/product/domain/user/service/AccountService.java
  src/main/java/org/zapply/product/global/config/SecurityConfig.java
  src/main/java/org/zapply/product/global/facebook/FacebookClient.java
  src/main/java/org/zapply/product/global/threads/ThreadsClient.java
Labels: ✨ Fix

#57 FEAT: 게시글을 예약발행한다.
  .github/workflows/ci.yml
  .gitignore
  src/main/java/org/zapply/product/domain/posting/controller/PostingController.java
  src/main/java/org/zapply/product/domain/posting/dto/request/ThreadsPostingRequest.java
  src/main/java/org/zapply/product/domain/posting/service/PostingService.java
  src/main/java/org/zapply/product/domain/project/controller/ProjectController.java
  src/main/java/org/zapply/product/domain/project/service/ProjectService.java
  src/main/java/org/zapply/product/domain/user/controller/AccountController.java
  src/main/java/org/zapply/product/domain/user/service/AccountService.java
  src/main/java/org/zapply/product/global/apiPayload/exception/GlobalErrorType.java
  src/main/java/org/zapply/product/global/scheduler/service/JobScheduler.java
  src/main/java/org/zapply/product/global/scheduler/service/JobSchedulerImpl.java
  src/main/java/org/zapply/product/global/threads/ThreadsPostingClient.java
Labels: 💫 Feature

#58 FEAT: 플랫폼(SNS)별로 게시글의 톤을 변환한다
  build.gradle
  src/main/java/org/zapply/product/ProductApplication.java
  src/main/java/org/zapply/product/domain/posting/controller/ToneTransferController.java
  src/main/java/org/zapply/product/domain/posting/dto/request/ToneTransferRequest.java
  src/main/java/org/zapply/product/domain/posting/entity/Posting.java
  src/main/java/org/zapply/product/domain/posting/service/ToneTransferService.java
  src/main/java/org/zapply/product/domain/user/entity/Account.java
  src/main/java/org/zapply/product/domain/user/enumerate/SNSType.java
  src/main/java/org/zapply/product/domain/user/repository/AccountRepository.java
  src/main/java/org/zapply/product/domain/user/service/AccountService.java
  src/main/java/org/zapply/product/global/apiPayload/exception/GlobalErrorType.java
  src/main/java/org/zapply/product/global/clova/ClovaAiClient.java
  src/main/java/org/zapply/product/global/clova/dto/ClovaMessage.java
  src/main/java/org/zapply/product/global/clova/dto/request/ClovaRequest.java
  src/main/java/org/zapply/product/global/clova/dto/response/ClovaResponse.java
  src/main/java/org/zapply/product/global/clova/dto/response/ClovaResult.java
  src/main/java/org/zapply/product/global/clova/dto/response/ClovaStatus.java
  src/main/java/org/zapply/product/global/clova/enuermerate/ClovaRole.java
  src/main/java/org/zapply/product/global/clova/enuermerate/SNSType.java
  src/main/java/org/zapply/product/global/threads/ThreadsPostingClient.java
  src/test/java/org/zapply/product/global/clova/ClovaAiClientTest.java
Labels: 💫 Feature

#55 FEAT: Threads에서 미디어 인사이트를 가져온다
  src/main/java/org/zapply/product/domain/posting/controller/PostingController.java
  src/main/java/org/zapply/product/domain/posting/dto/response/ThreadsInsightResponse.java
  src/main/java/org/zapply/product/global/apiPayload/exception/GlobalErrorType.java
  src/main/java/org/zapply/product/global/threads/ThreadsInsightClient.java
Labels: 💫 Feature

#62 FEAT: 사용자 계정 연동을 해지한다.
  src/main/java/org/zapply/product/domain/user/controller/AccountController.java
  src/main/java/org/zapply/product/domain/user/service/AccountService.java
  src/main/java/org/zapply/product/global/vault/VaultClient.java
  src/test/java/org/zapply/product/domain/user/service/AccountServiceTest.java
  src/test/java/org/zapply/product/global/objectStorage/controller/ImageControllerTest.java
Labels: 💫 Feature

#68 FIX: 로그인 시 response를 수정한다
  src/main/java/org/zapply/product/domain/user/controller/AccountController.java
  src/main/java/org/zapply/product/domain/user/dto/response/TokenResponse.java
  src/main/java/org/zapply/product/global/security/jwt/JwtProvider.java
Labels: ✨ Fix

#60 FEAT: 사용자 정보 및 계정 연결 정보를 조회한다.
  src/main/java/org/zapply/product/domain/user/controller/AuthController.java
  src/main/java/org/zapply/product/domain/user/dto/response/AccountInfo.java
  src/main/java/org/zapply/product/domain/user/dto/response/AccountsInfoResponse.java
  src/main/java/org/zapply/product/domain/user/repository/AccountRepository.java
  src/main/java/org/zapply/product/domain/user/service/AccountService.java
  src/main/java/org/zapply/product/global/security/AuthDetails.java
  src/main/java/org/zapply/product/global/security/oAuth2/CustomOAuth2UserService.java
  src/test/java/org/zapply/product/domain/user/service/AccountServiceTest.java
Labels: 💫 Feature

#71 #69 Feat: 클라리언트에게 redirect 시켜준다
  src/main/java/org/zapply/product/domain/user/controller/AccountController.java
  src/main/java/org/zapply/product/global/security/oAuth2/OAuth2SuccessHandler.java
Labels: 💫 Feature, ✨ Fix

#73 REFACTOR: 로그인 응답 구조에 연동된 계정 정보와, 사용자 정보를 포함시킨다
  src/main/java/org/zapply/product/domain/user/controller/AuthController.java
  src/main/java/org/zapply/product/domain/user/dto/response/LoginResponse.java
  src/main/java/org/zapply/product/domain/user/dto/response/MemberResponse.java
  src/main/java/org/zapply/product/domain/user/dto/response/TokenResponse.java
  src/main/java/org/zapply/product/domain/user/service/AuthService.java
  src/main/java/org/zapply/product/global/security/jwt/JwtProvider.java
  src/main/java/org/zapply/product/global/security/oAuth2/OAuth2SuccessHandler.java
Labels: 🔨 Refactor

#75 FEAT: 게시글을 기반으로 제목을 추천한다
  src/main/java/org/zapply/product/domain/posting/controller/ClovaController.java
  src/main/java/org/zapply/product/domain/posting/service/ClovaService.java
  src/test/java/org/zapply/product/global/clova/ClovaAiClientTest.java
Labels: 💫 Feature

#76 FEAT: 마이페이지에서 나의 정보를 수정한다
  src/main/java/org/zapply/product/domain/user/controller/AccountController.java
  src/main/java/org/zapply/product/domain/user/controller/AuthController.java
  src/main/java/org/zapply/product/domain/user/controller/MemberController.java
  src/main/java/org/zapply/product/domain/user/dto/request/MemberRequest.java
  src/main/java/org/zapply/product/domain/user/dto/response/MemberResponse.java
  src/main/java/org/zapply/product/domain/user/entity/Credential.java
  src/main/java/org/zapply/product/domain/user/entity/Member.java
  src/main/java/org/zapply/product/domain/user/service/AccountService.java
  src/main/java/org/zapply/product/domain/user/service/AuthService.java
  src/main/java/org/zapply/product/domain/user/service/CredentialService.java
  src/main/java/org/zapply/product/domain/user/service/MemberService.java
Labels: 💫 Feature, ✨ Fix

#80 FEAT: 링크드인 계정을 연동한다
  src/main/java/org/zapply/product/domain/posting/controller/PostingController.java
  src/main/java/org/zapply/product/domain/posting/service/PostingQueryService.java
  src/main/java/org/zapply/product/domain/posting/service/PostingService.java
  src/main/java/org/zapply/product/domain/user/controller/AccountController.java
  src/main/java/org/zapply/product/domain/user/service/AccountService.java
  src/main/java/org/zapply/product/global/apiPayload/exception/GlobalErrorType.java
  src/main/java/org/zapply/product/global/clova/enuermerate/SNSType.java
  src/main/java/org/zapply/product/global/config/SecurityConfig.java
  src/main/java/org/zapply/product/global/snsClients/facebook/FacebookClient.java
  src/main/java/org/zapply/product/global/snsClients/facebook/FacebookProfile.java
  src/main/java/org/zapply/product/global/snsClients/facebook/FacebookToken.java
  src/main/java/org/zapply/product/global/snsClients/linkedin/LinkedinClient.java
  src/main/java/org/zapply/product/global/snsClients/linkedin/LinkedinToken.java
  src/main/java/org/zapply/product/global/snsClients/linkedin/LinkedinUserInfo.java
  src/main/java/org/zapply/product/global/snsClients/threads/ThreadsClient.java
  src/main/java/org/zapply/product/global/snsClients/threads/ThreadsInsightClient.java
  src/main/java/org/zapply/product/global/snsClients/threads/ThreadsMediaClient.java
  src/main/java/org/zapply/product/global/snsClients/threads/ThreadsMediaResponse.java
  src/main/java/org/zapply/product/global/snsClients/threads/ThreadsPostingClient.java
  src/main/java/org/zapply/product/global/snsClients/threads/ThreadsProfile.java
  src/main/java/org/zapply/product/global/snsClients/threads/ThreadsReplyClient.java
  src/main/java/org/zapply/product/global/snsClients/threads/ThreadsToken.java
  src/main/java/org/zapply/product/global/threads/ThreadsReplyClient.java
Labels: 💫 Feature

#83 FIX: 페이스북 연동 콜백 주소에서 authdetail를 삭제한다
  src/main/java/org/zapply/product/domain/user/controller/AccountController.java
Labels: ✨ Fix

#79 TEST: 회원가입 테스트 코드를 작성한다
  src/main/java/org/zapply/product/domain/user/dto/request/AuthRequest.java
  src/test/java/org/zapply/product/domain/member/controller/AuthControllerTest.java
  src/test/java/org/zapply/product/domain/member/service/AccountServiceTest.java
  src/test/java/org/zapply/product/domain/member/service/AuthServiceTest.java
  src/test/java/org/zapply/product/domain/member/service/CredentialServiceTest.java
  src/test/java/org/zapply/product/domain/member/service/MemberServiceTest.java
  src/test/java/org/zapply/product/domain/member/util/AuthRequestUtilTest.java
  src/test/java/org/zapply/product/domain/member/util/MemberUtilTest.java
Labels: ✅ Test

#93 Feat: 인스타그램 계정을 연동한다
  src/main/java/org/zapply/product/domain/user/controller/AccountController.java
  src/main/java/org/zapply/product/domain/user/entity/Account.java
  src/main/java/org/zapply/product/domain/user/repository/AccountRepository.java
  src/main/java/org/zapply/product/domain/user/service/AccountService.java
  src/main/java/org/zapply/product/global/apiPayload/exception/GlobalErrorType.java
  src/main/java/org/zapply/product/global/snsClients/instagram/InstagramBusinessResponse.java
  src/main/java/org/zapply/product/global/snsClients/instagram/InstagramClient.java
  src/main/java/org/zapply/product/global/snsClients/instagram/InstagramProfile.java
  src/main/java/org/zapply/product/global/snsClients/instagram/InstagramToken.java
Labels: 💫 Feature

#98 FIX: 인스타그램 Callback uri을 삭제하고 연동을 끊는다
  src/main/java/org/zapply/product/domain/user/controller/AccountController.java
  src/main/java/org/zapply/product/domain/user/service/AccountService.java
Labels: ✨ Fix

#96 FEAT: 인스타그램에 게시글을 발행하고 조회한다
  src/main/java/org/zapply/product/domain/posting/controller/PostingController.java
  src/main/java/org/zapply/product/domain/posting/dto/request/PostingRequest.java
  src/main/java/org/zapply/product/domain/posting/dto/response/PostingDetailResponse.java
  src/main/java/org/zapply/product/domain/posting/service/InstagramPostingService.java
  src/main/java/org/zapply/product/domain/posting/service/PostingQueryService.java
  src/main/java/org/zapply/product/domain/posting/service/PostingService.java
  src/main/java/org/zapply/product/domain/posting/service/PublishPostingService.java
  src/main/java/org/zapply/product/domain/user/dto/response/AccountInfo.java
  src/main/java/org/zapply/product/domain/user/entity/Account.java
  src/main/java/org/zapply/product/domain/user/service/AccountService.java
  src/main/java/org/zapply/product/global/snsClients/facebook/FacebookClient.java
  src/main/java/org/zapply/product/global/snsClients/facebook/FacebookProfile.java
  src/main/java/org/zapply/product/global/snsClients/instagram/InstagramMediaClient.java
  src/main/java/org/zapply/product/global/snsClients/instagram/InstagramMediaResponse.java
  src/main/java/org/zapply/product/global/snsClients/instagram/InstagramPostingClient.java
  src/main/java/org/zapply/product/global/snsClients/instagram/InstagramPostingResponse.java
  src/main/java/org/zapply/product/global/snsClients/threads/ThreadsPostingClient.java
Labels: 💫 Feature

#101 FEAT: 플랫폼 글 변환을 동시에 수행하도록 수정한다
  src/main/java/org/zapply/product/domain/posting/controller/ClovaController.java
  src/main/java/org/zapply/product/domain/posting/dto/request/ToneTransferRequest.java
  src/main/java/org/zapply/product/domain/posting/dto/response/ToneTransferResponse.java
  src/main/java/org/zapply/product/domain/posting/service/ClovaService.java
  src/test/java/org/zapply/product/domain/posting/service/PostingQueryServiceTest.java
Labels: ✨ Fix

#102 FIX: 구글 로그인 응답 방식을 변경한다
  src/main/java/org/zapply/product/global/security/oAuth2/OAuth2SuccessHandler.java
Labels: 💫 Feature

#108 FEAT: 페이스북에 글을 게시한다
  src/main/java/org/zapply/product/domain/posting/controller/PostingController.java
  src/main/java/org/zapply/product/domain/posting/service/FacebookPostingService.java
  src/main/java/org/zapply/product/domain/posting/service/PublishPostingService.java
  src/main/java/org/zapply/product/domain/user/service/AccountService.java
  src/main/java/org/zapply/product/global/snsClients/facebook/service/FacebookClient.java
  src/main/java/org/zapply/product/global/snsClients/facebook/service/FacebookMediaClient.java
  src/main/java/org/zapply/product/global/snsClients/facebook/service/FacebookPostingClient.java
  src/test/java/org/zapply/product/global/snsClients/facebook/FacebookClientTest.java
  src/test/java/org/zapply/product/global/snsClients/facebook/FacebookMediaClientTest.java
  src/test/java/org/zapply/product/global/snsClients/facebook/FacebookPostingClientTest.java
Labels: 💫 Feature

#109 Fix: 페이징 hasNext 수정
  src/main/java/org/zapply/product/domain/posting/controller/PostingController.java
  src/main/java/org/zapply/product/domain/posting/service/PostingQueryService.java
Labels: ✨ Fix

#114 FEAT: 페이스북에서 발행한 글을 불러온다.
  src/main/java/org/zapply/product/domain/posting/controller/PostingController.java
  src/main/java/org/zapply/product/domain/posting/service/FacebookPostingService.java
  src/main/java/org/zapply/product/domain/posting/service/PostingQueryService.java
  src/main/java/org/zapply/product/domain/user/controller/AccountController.java
  src/main/java/org/zapply/product/domain/user/entity/Account.java
  src/main/java/org/zapply/product/domain/user/service/AccountService.java
  src/main/java/org/zapply/product/global/snsClients/facebook/FacebookMediaResponse.java
  src/main/java/org/zapply/product/global/snsClients/facebook/FacebookPage.java
  src/main/java/org/zapply/product/global/snsClients/facebook/FacebookProfile.java
  src/main/java/org/zapply/product/global/snsClients/facebook/service/FacebookClient.java
  src/main/java/org/zapply/product/global/snsClients/facebook/service/FacebookMediaClient.java
  src/main/java/org/zapply/product/global/snsClients/facebook/service/FacebookPostingClient.java
  src/main/java/org/zapply/product/global/vault/VaultClient.java
Labels: 💫 Feature

#119 FIX: 페이스북 토큰 발급 response를 변경한다
  src/main/java/org/zapply/product/domain/user/controller/AccountController.java
Labels: ✨ Fix
