Repository Za-ply/Zaply-server, pull requests merged in 2025-04, with the labels that each got.

#3 FEAT: #2 배포환경을 코드로 관리한다
  .gitignore
  terraform/.gitignore
  terraform/main.tf
  terraform/network_module/outputs.tf
  terraform/network_module/providers.tf
  terraform/network_module/subnet.tf
  terraform/network_module/vpc.tf
  terraform/server_module/providers.tf
  terraform/server_module/server.tf
Labels: 🌏 Deploy

#8 FEAT: 자체 회원가입, 로그인, 로그아웃, 토큰 재발급 기능을 구현한다
  build.gradle
  src/main/java/org/zapply/product/ProductApplication.java
  src/main/java/org/zapply/product/domain/user/controller/AuthController.java
  src/main/java/org/zapply/product/domain/user/dto/request/AuthRequest.java
  src/main/java/org/zapply/product/domain/user/dto/request/SignInRequest.java
  src/main/java/org/zapply/product/domain/user/dto/response/MemberResponse.java
  src/main/java/org/zapply/product/domain/user/dto/response/TokenResponse.java
  src/main/java/org/zapply/product/domain/user/entity/Credential.java
  src/main/java/org/zapply/product/domain/user/entity/Member.java
  src/main/java/org/zapply/product/domain/user/enumerate/MemberType.java
  src/main/java/org/zapply/product/domain/user/repository/CredentialRepository.java
  src/main/java/org/zapply/product/domain/user/repository/UserRepository.java
  src/main/java/org/zapply/product/domain/user/service/AuthService.java
  src/main/java/org/zapply/product/domain/user/service/CredentialService.java
  src/main/java/org/zapply/product/domain/user/service/UserService.java
  src/main/java/org/zapply/product/global/BaseTimeEntity.java
  src/main/java/org/zapply/product/global/apiPayload/ApiControllerAdvice.java
  src/main/java/org/zapply/product/global/apiPayload/exception/GlobalErrorType.java
  src/main/java/org/zapply/product/global/config/RedisConfig.java
  src/main/java/org/zapply/product/global/config/SecurityConfig.java
  src/main/java/org/zapply/product/global/redis/RedisClient.java
  src/main/java/org/zapply/product/global/security/AuthDetails.java
  src/main/java/org/zapply/product/global/security/AuthDetailsService.java
  src/main/java/org/zapply/product/global/security/ExceptionFilter.java
  src/main/java/org/zapply/product/global/security/jwt/JwtAccessDeniedHandler.java
  src/main/java/org/zapply/product/global/security/jwt/JwtAuthenticationHandler.java
  src/main/java/org/zapply/product/global/security/jwt/JwtFilter.java
  src/main/java/org/zapply/product/global/security/jwt/JwtProvider.java
  src/main/resources/application.properties
Labels: 💫 Feature

#10 CHORE: swagger를 통해 api를 명세화한다.
  build.gradle
  src/main/java/org/zapply/product/global/config/SwaggerConfig.java
  terraform/.gitignore
  terraform/server_module/server.tf
Labels: 🛠️ Chore

#12 FEAT: 기본 엔티티를 작성한다.
  src/main/java/org/zapply/product/domain/posting/entity/Image.java
  src/main/java/org/zapply/product/domain/posting/entity/Posting.java
  src/main/java/org/zapply/product/domain/posting/enumerate/PostingState.java
  src/main/java/org/zapply/product/domain/project/entity/Project.java
  src/main/java/org/zapply/product/domain/user/entity/Account.java
  src/main/java/org/zapply/product/domain/user/entity/Member.java
  src/main/java/org/zapply/product/domain/user/enumerate/LoginType.java
  src/main/java/org/zapply/product/domain/user/enumerate/SNSType.java
  terraform/.gitignore
Labels: 💫 Feature

#15 CICD: ci/cd 파이프라인을 구현한다.
  .github/workflow/ci-cd.yml
  Dockerfile
Labels: 🌏 Deploy
